---
# tasks file for k3s_agent
- name: Get k3s binary
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: /usr/local/bin/k3s
    mode: "0755"

- name: Add systemd service file
  become: true
  ansible.builtin.template:
    src: k3s-agent-service.j2
    dest: /etc/systemd/system/k3s.service
    mode: "0666"

- name: Add defaults file
  become: true
  ansible.builtin.template:
    src: k3s-defaults.j2
    dest: /etc/default/k3s
    mode: "0666"

- name: Enable k3s-service
  become: true
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true
    daemon_reload: true
